### ISSUE TITLE
Problem with new Pywis PubSub  version

### ISSUE THREAD

**Issue by mgiannoni** [World-Meteorological-Organization/pywis-pubsub#38]
```
$ pywis-pubsub --help
Traceback (most recent call last):
  File "/usr/local/bin/pywis-pubsub", line 5, in <module>
    from pywis_pubsub import cli
  File "/usr/local/lib/python3.8/site-packages/pywis_pubsub/__init__.py", line 28, in <module>
    from pywis_pubsub.subscribe import subscribe
  File "/usr/local/lib/python3.8/site-packages/pywis_pubsub/subscribe.py", line 39, in <module>
    from pywis_pubsub.message import get_link, get_data
ImportError: cannot import name 'get_link' from 'pywis_pubsub.message' (/usr/local/lib/python3.8/site-packages/pywis_pubsub/message.py)
```

**Comment by mgiannoni** [comment]
This is running in a container:
```
FROM python:3.8
RUN pip install pywis-pubsub && \
    addgroup --gid 1004 wis2box && \
    adduser --uid 1004 --ingroup wis2box --gecos "" --disabled-password wis2box
COPY --chown=wis2box:wis2box local.yml /app/
WORKDIR /app
USER wis2box
CMD ["pywis-pubsub", "subscribe", "--config", "local.yml","--download","--verbosity","DEBUG"]


```

**Comment by tomkralidis** [comment]
@mgiannoni is this still an issue?  Can you try using 0.5.0?
